server:
  port: 8761

spring:
  application:
    name: egobug-register-eureka
eureka:
  client:
    # 是否从其他eureka获取数据
    fetch-registry: false
    # 是否注册其他eureka实例
    register-with-eureka: false
    # eureka注册的地址
    service-url:
      defaultZone: http://localhost:8761/eureka/
